# Generated by Django 4.2.7 on 2023-11-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='equipo',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='equipo',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='technical',
            old_name='equipo',
            new_name='team',
        ),
        migrations.AddField(
            model_name='nacionality',
            name='technical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fifa.technical'),
        ),
    ]
