# Generated by Django 4.2.7 on 2023-11-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_rename_equipo_player_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=50, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Posicion', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'ordering': ['id'], 'verbose_name': 'tecnico', 'verbose_name_plural': 'tecnicos'},
        ),
        migrations.RemoveField(
            model_name='nacionality',
            name='code',
        ),
        migrations.RemoveField(
            model_name='nacionality',
            name='technical',
        ),
        migrations.AddField(
            model_name='technical',
            name='nacionality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fifa.nacionality'),
        ),
        migrations.AlterField(
            model_name='nacionality',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nacionality',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Bandera del equipo'),
        ),
        migrations.AddField(
            model_name='technical',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fifa.role'),
        ),
    ]
