# Generated by Django 4.2.7 on 2023-11-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_role_alter_position_options_alter_technical_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_name',
            new_name='last_name_player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='name_player',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='name_position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_in_which_you_play',
        ),
        migrations.RemoveField(
            model_name='position',
            name='player',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fifa.position'),
        ),
        migrations.AddField(
            model_name='technical',
            name='last_name_technical',
            field=models.CharField(default='', max_length=20, verbose_name='Apellido del tecnico'),
        ),
        migrations.AddField(
            model_name='technical',
            name='name_technical',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre del tecnico'),
        ),
        migrations.AlterField(
            model_name='nacionality',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='nacionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.nacionality'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.role'),
        ),
    ]
